name: flutter_ignitr
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dcli: ^6.1.0
  path: ^1.9.0
  http: ^1.2.2
  archive: ^3.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null

executables:
  flutter_ignitr: main
  ignitr: main
