name: ignitr_cli
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/thedevsbuddy/ignitr_cli

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.6.1
  args: ^2.6.0
  dcli: ^6.1.0
  flutter:
    sdk: flutter
  http: ^1.3.0
  path: ^1.9.0
  pluralize: ^0.0.8
  recase: ^4.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

executables:
  ignitr: main
